"""
Tool: get_basin_attributes
Read hydrological and climate attributes for a basin from cached NC files.
Supports CAMELS-US, LamaH-CE, and selfmade (hydrodatasource) datasets.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Variable name mappings: standardized_name -> dataset-specific names (tried in order)
_VAR_MAP: dict[str, list[str]] = {
    "aridity":       ["aridity", "arid_1", "ari_ix_sav"],
    "runoff_ratio":  ["runoff_ratio", "run_ratio", "run_mm_syr"],   # run_mm_syr needs normalization
    "baseflow_index":["baseflow_index", "bfi_mean", "bfi"],
    "frac_snow":     ["frac_snow", "snw_pc_syr"],
    "p_mean":        ["p_mean", "p_mean_mm", "pre_mm_syr"],
    "pet_mean":      ["pet_mean", "pet_mm_syr"],
    "slope_mean":    ["slope_mean", "slope_mkm1", "slp_dg_sav"],
    "area_km2":      ["area_gages2", "area_km2", "area"],
}

# Dataset name aliases -> cache file stem (without '_attributes.nc')
_DATASET_CACHE_STEMS: dict[str, list[str]] = {
    "camels_us":             ["camelsus", "camels_us"],
    "camelsus":              ["camelsus", "camels_us"],
    "lamahce":               ["lamahce"],
    "lamahe":                ["lamahce"],
    "selfmade":              ["songliaorrevent"],
    "selfmadehydrodataset":  ["songliaorrevent"],
    "hydrodatasource":       ["songliaorrevent"],
}


def _find_cache_file(data_source: str, cache_dir: Path) -> Path | None:
    """Locate the cached attributes NC file for a given dataset."""
    ds_lower = data_source.lower().replace("-", "").replace(" ", "")
    stems = _DATASET_CACHE_STEMS.get(ds_lower, [ds_lower])

    for stem in stems:
        for candidate in [
            cache_dir / f"{stem}_attributes.nc",
            cache_dir / f"{stem}.nc",
        ]:
            if candidate.exists():
                return candidate

    # Fallback: glob for anything matching
    matches = list(cache_dir.glob(f"*{ds_lower.replace('_','')}*attributes*.nc"))
    if matches:
        return matches[0]
    return None


def _read_var(ds, std_name: str) -> float | None:
    """Try multiple variable name aliases and return the first match."""
    for alias in _VAR_MAP.get(std_name, [std_name]):
        if alias in ds:
            try:
                return float(ds[alias].values)
            except Exception:
                pass
    return None


def _classify_climate(attrs: dict) -> str:
    """Derive a simple climate label from aridity and frac_snow."""
    aridity    = attrs.get("aridity")
    frac_snow  = attrs.get("frac_snow", 0.0) or 0.0
    runoff     = attrs.get("runoff_ratio")

    if aridity is None:
        return "unknown"

    if aridity < 0.6:
        return "humid_cold" if frac_snow > 0.1 else "humid_warm"
    elif aridity < 1.0:
        return "sub_humid_mediterranean"
    else:
        return "semiarid_arid"


def get_basin_attributes(
    basin_id: str,
    data_source: str = "camels_us",
    _cfg: dict | None = None,
) -> dict:
    """Get climate and hydrological attributes for a basin from the cached dataset.

    Reads pre-cached NC attribute files generated by hydrodatasource.
    Supports CAMELS-US, LamaH-CE, and selfmade (songliao) datasets.

    Args:
        basin_id: Basin identifier (e.g. "12025000" for CAMELS-US)
        data_source: Dataset name, default "camels_us"

    Returns:
        {
          "basin_id": str,
          "data_source": str,
          "aridity": float,          # Aridity index (PET/P); >1 = arid
          "runoff_ratio": float,     # Mean annual Q/P ratio
          "baseflow_index": float,   # BFI (0-1)
          "frac_snow": float,        # Fraction of precip as snow
          "p_mean": float,           # Mean daily precip (mm/d)
          "pet_mean": float,         # Mean daily PET (mm/d)
          "slope_mean": float,       # Mean basin slope
          "area_km2": float,         # Basin area (km2)
          "climate_zone": str,       # Derived label
          "all_attributes": dict,    # All raw variables (may be large)
          "note": str                # Any caveats
        }
    """
    try:
        import xarray as xr
    except ImportError:
        return {"error": "xarray not installed", "success": False}

    cfg = _cfg or {}
    cache_dir = Path(cfg.get("paths", {}).get("cache_dir", Path.home() / ".cache"))

    nc_path = _find_cache_file(data_source, cache_dir)
    if nc_path is None:
        return {
            "error": f"No cached attribute file found for dataset '{data_source}' in {cache_dir}",
            "basin_id": basin_id,
            "success": False,
        }

    try:
        ds_full = xr.open_dataset(nc_path)
    except Exception as e:
        return {"error": f"Cannot open {nc_path}: {e}", "success": False}

    # Select the basin
    basin_coord = ds_full["basin"].values
    basin_id_str = str(basin_id)

    if basin_id_str not in basin_coord:
        # Try zero-padded match
        candidates = [str(b) for b in basin_coord if str(b).lstrip("0") == basin_id_str.lstrip("0")]
        if candidates:
            basin_id_str = candidates[0]
        else:
            ds_full.close()
            return {
                "error": f"Basin '{basin_id}' not found in {nc_path.name}",
                "available_sample": [str(b) for b in basin_coord[:5]],
                "success": False,
            }

    ds = ds_full.sel(basin=basin_id_str)

    # Extract standardized attributes
    attrs: dict[str, Any] = {}
    for std_name in _VAR_MAP:
        val = _read_var(ds, std_name)
        if val is not None:
            attrs[std_name] = round(val, 6)

    attrs["climate_zone"] = _classify_climate(attrs)

    # All raw attributes (for reference)
    all_raw: dict[str, Any] = {}
    for v in ds_full.data_vars:
        try:
            raw = float(ds[v].values)
            if raw == raw:  # filter NaN
                all_raw[v] = round(raw, 4)
        except Exception:
            pass

    ds_full.close()

    return {
        "basin_id": basin_id,
        "data_source": data_source,
        **attrs,
        "all_attributes": all_raw,
        "source_file": nc_path.name,
        "success": True,
    }


get_basin_attributes.__agent_hint__ = (
    "Returns aridity, runoff_ratio, baseflow_index, frac_snow, climate_zone for a basin. "
    "Call BEFORE llm_calibrate to get basin characteristics for informed parameter range setting. "
    "Use climate_zone + aridity + frac_snow to reason about appropriate XAJ/GR4J parameter ranges."
)
