"""
Author: HydroAgent Team
Date: 2026-02-08
Description: Auto-discovery of tool functions and schema generation.
             Scans both tools/*.py (core tools) and skills/*/*.py (skill tools).
             Priority-based conflict resolution prevents lower-priority tools from
             silently overriding higher-priority ones.
"""

import importlib
import inspect
import logging
import pkgutil
from pathlib import Path
from typing import Any, Callable, get_type_hints

logger = logging.getLogger(__name__)

# ── Priority levels ───────────────────────────────────────────────────────────
# Higher number = higher priority. When two tools share the same name, the
# higher-priority one wins. Equal priority: later registration wins (update).
PRIORITY_TOOLS   = 20   # hydroagent/tools/*.py  — core infrastructure tools
PRIORITY_SKILLS  = 10   # hydroagent/skills/*/*.py — workflow skill tools
PRIORITY_DYNAMIC = 5    # dynamically generated by create_skill (lower trust)

# ── Registries ────────────────────────────────────────────────────────────────
# {tool_name: function}
_TOOLS: dict[str, Callable] = {}
# {tool_name: {"source": str, "priority": int, "module": str}}
_TOOL_META: dict[str, dict] = {}


def discover_tools(workspace: "Path | None" = None) -> dict[str, Callable]:
    """Scan tool modules in tools/ and skills/*/ and register public functions.

    Priority order (high -> low):
      1. tools/*.py          — PRIORITY_TOOLS (20)
      2. skills/*/*.py       — PRIORITY_SKILLS (10)
      3. external single_file plugins from PluginRegistry — PRIORITY_DYNAMIC (5)

    Dynamic skills created at runtime (create_skill) have a marker file
    '.dynamic' in their directory and are registered at PRIORITY_DYNAMIC (5).

    Args:
        workspace: Optional path used to locate the local plugin registry.
    """
    if _TOOLS:
        return _TOOLS

    package_dir = Path(__file__).parent

    # 1. Core tools (highest priority)
    _scan_dir(package_dir, "hydroagent.tools", PRIORITY_TOOLS)

    # 2. Skill tools
    skills_dir = package_dir.parent / "skills"
    if skills_dir.exists():
        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir() or skill_dir.name.startswith("_"):
                continue
            # Dynamic skills (created by create_skill) get lower priority
            priority = (
                PRIORITY_DYNAMIC
                if (skill_dir / ".dynamic").exists()
                else PRIORITY_SKILLS
            )
            _scan_dir(skill_dir, f"hydroagent.skills.{skill_dir.name}", priority)

    # 3. External single_file plugins from PluginRegistry
    try:
        from hydroagent.utils.plugin_registry import PluginRegistry
        registry = PluginRegistry(workspace)
        for plugin in registry.list_plugins():
            if not plugin.get("enabled", True):
                continue
            if plugin.get("type") == "single_file":
                _load_single_file_plugin(plugin)
    except Exception as exc:
        logger.debug("[tools] external plugin scan skipped: %s", exc)

    logger.info("Discovered %d tools: %s", len(_TOOLS), list(_TOOLS.keys()))
    return _TOOLS


def _load_single_file_plugin(plugin: dict) -> None:
    """Load public functions from a single .py file as PRIORITY_DYNAMIC tools."""
    import importlib.util
    import sys

    name = plugin.get("name", "<unknown>")
    file_path = Path(plugin.get("path", ""))
    if not file_path.exists():
        logger.warning("[tools] single_file plugin '%s' not found: %s", name, file_path)
        return

    # Add the file's directory to sys.path so relative imports inside it work
    pkg_dir = str(file_path.parent)
    if pkg_dir not in sys.path:
        sys.path.insert(0, pkg_dir)

    mod_key = f"_hydroagent_plugin_{name}_tool"
    try:
        spec = importlib.util.spec_from_file_location(mod_key, file_path)
        if spec is None or spec.loader is None:
            return
        mod = importlib.util.module_from_spec(spec)
        sys.modules[mod_key] = mod
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
        count = 0
        for fn_name, obj in inspect.getmembers(mod, inspect.isfunction):
            if fn_name.startswith("_"):
                continue
            if obj.__module__ != mod.__name__:
                continue
            _register_tool(fn_name, obj, source=str(file_path), priority=PRIORITY_DYNAMIC)
            count += 1
        if count:
            logger.info("[tools] single_file plugin '%s' registered %d function(s)", name, count)
    except Exception as exc:
        logger.warning("[tools] failed to load single_file plugin '%s': %s", name, exc)


def _scan_dir(dir_path: Path, module_prefix: str, priority: int):
    """Scan a directory for tool modules and register public functions.

    Conflict resolution:
    - If tool_name already registered with higher priority -> keep existing, log warning
    - If tool_name already registered with equal or lower priority -> overwrite, log info
    """
    for module_info in pkgutil.iter_modules([str(dir_path)]):
        if module_info.name.startswith("_"):
            continue
        module_name = f"{module_prefix}.{module_info.name}"
        try:
            module = importlib.import_module(module_name)
            for name, obj in inspect.getmembers(module, inspect.isfunction):
                if name.startswith("_"):
                    continue
                if obj.__module__ != module.__name__:
                    continue
                _register_tool(name, obj, source=module_name, priority=priority)
        except Exception as e:
            logger.warning("Failed to load tool module %s: %s", module_name, e)


def _register_tool(name: str, fn: Callable, source: str, priority: int):
    """Register a single tool with conflict resolution."""
    if name in _TOOLS:
        existing = _TOOL_META[name]
        if priority > existing["priority"]:
            logger.info(
                "[tools] override '%s': %s (p=%d) -> %s (p=%d)",
                name, existing["source"], existing["priority"], source, priority,
            )
        elif priority < existing["priority"]:
            logger.warning(
                "[tools] conflict ignored: '%s' from '%s' (p=%d) lost to existing '%s' (p=%d)",
                name, source, priority, existing["source"], existing["priority"],
            )
            return  # keep existing higher-priority tool
        else:
            # Equal priority — later registration wins (normal update/reload case)
            logger.debug(
                "[tools] update '%s': %s -> %s (same priority %d)",
                name, existing["source"], source, priority,
            )

    _TOOLS[name] = fn
    _TOOL_META[name] = {"source": source, "priority": priority, "module": fn.__module__}
    logger.debug("Registered tool: %s (from %s, p=%d)", name, source, priority)


def reload_tools() -> dict[str, Callable]:
    """Clear registry and re-discover all tools.

    Called after creating new skill/tool files so they are immediately available.
    """
    _TOOLS.clear()
    _TOOL_META.clear()
    # Clear Python's module cache for tools and skills
    import sys
    to_remove = [
        k for k in sys.modules
        if (k.startswith("hydroagent.tools.") or k.startswith("hydroagent.skills."))
        and k not in ("hydroagent.tools", "hydroagent.skills")
    ]
    for k in to_remove:
        del sys.modules[k]
    return discover_tools()


def get_tool_schemas() -> list[dict[str, Any]]:
    """Generate OpenAI function calling schemas for all registered tools."""
    tools = discover_tools()
    schemas = []
    for name, fn in tools.items():
        schema = fn_to_schema(fn)
        if schema:
            schemas.append(schema)
    return schemas


def get_tool_registry_info() -> list[dict]:
    """Return metadata for all registered tools (name, source, priority, description)."""
    discover_tools()
    result = []
    for name, meta in sorted(_TOOL_META.items(), key=lambda x: (-x[1]["priority"], x[0])):
        fn = _TOOLS.get(name)
        doc = (fn.__doc__ or "").strip() if fn else ""
        # First non-empty line as short description; full doc as long description
        lines = [l.strip() for l in doc.splitlines() if l.strip()]
        short = lines[0] if lines else ""
        full  = doc
        zh_name = getattr(fn, "__zh_name__", "") if fn else ""
        zh_desc = getattr(fn, "__zh_desc__", "") if fn else ""
        result.append({"name": name, **meta, "description": short, "doc": full, "zh_name": zh_name, "zh_desc": zh_desc})
    return result


def fn_to_schema(fn: Callable) -> dict[str, Any] | None:
    """Convert a function's signature + docstring to OpenAI tool schema.

    Parameters starting with '_' are treated as internal (injected at runtime)
    and excluded from the schema.
    """
    try:
        sig = inspect.signature(fn)
        hints = get_type_hints(fn)
        doc = inspect.getdoc(fn) or ""

        description, param_docs = _parse_docstring(doc)

        hint = getattr(fn, "__agent_hint__", None)
        if hint:
            description = description.rstrip(".") + ". " + hint.strip()

        properties = {}
        required = []

        for param_name, param in sig.parameters.items():
            if param_name.startswith("_"):
                continue

            param_type = hints.get(param_name, Any)
            json_type = _python_type_to_json(param_type)
            param_desc = param_docs.get(param_name, "")

            prop: dict[str, Any] = {"type": json_type}
            if param_desc:
                prop["description"] = param_desc

            if param.default is inspect.Parameter.empty:
                required.append(param_name)
            elif param.default is not None:
                prop["default"] = param.default

            if json_type == "array":
                item_type = _get_list_item_type(param_type)
                if item_type:
                    prop["items"] = {"type": item_type}

            properties[param_name] = prop

        schema = {
            "type": "function",
            "function": {
                "name": fn.__name__,
                "description": description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                },
            },
        }
        return schema

    except Exception as e:
        logger.warning("Failed to generate schema for %s: %s", fn.__name__, e)
        return None


_PARAM_DESC_MAX = 100


def _parse_docstring(doc: str) -> tuple[str, dict[str, str]]:
    """Parse docstring into description and parameter docs."""
    lines = doc.strip().split("\n")
    description_lines = []
    param_docs: dict[str, str] = {}
    in_args = False

    for line in lines:
        stripped = line.strip()
        if stripped.lower().startswith("args:"):
            in_args = True
            continue
        if stripped.lower().startswith("returns:"):
            in_args = False
            continue
        if in_args:
            import re
            match = re.match(r"(\w+)(?:\s*\([^)]*\))?\s*:\s*(.*)", stripped)
            if match:
                desc = match.group(2).strip()
                if len(desc) > _PARAM_DESC_MAX:
                    desc = desc[:_PARAM_DESC_MAX - 3] + "..."
                param_docs[match.group(1)] = desc
        elif not stripped.startswith("---"):
            description_lines.append(stripped)

    full_desc = " ".join(description_lines).strip()
    dot_idx = full_desc.find(". ")
    if 0 < dot_idx < 120:
        description = full_desc[: dot_idx + 1]
    else:
        description = full_desc[:120]
    return description, param_docs


def _python_type_to_json(python_type) -> str:
    """Convert Python type hint to JSON Schema type."""
    import types
    import typing
    origin = getattr(python_type, "__origin__", None)

    if origin is list or origin is typing.List:
        return "array"
    if origin is dict or origin is typing.Dict:
        return "object"
    if origin is typing.Union:
        args = python_type.__args__
        non_none = [a for a in args if a is not type(None)]
        if non_none:
            return _python_type_to_json(non_none[0])
    if isinstance(python_type, types.UnionType):
        args = python_type.__args__
        non_none = [a for a in args if a is not type(None)]
        if non_none:
            return _python_type_to_json(non_none[0])

    if python_type is dict:
        return "object"
    if python_type is str:
        return "string"
    if python_type is int:
        return "integer"
    if python_type is float:
        return "number"
    if python_type is bool:
        return "boolean"

    return "string"


def _get_list_item_type(python_type) -> str | None:
    args = getattr(python_type, "__args__", None)
    if args and len(args) > 0:
        return _python_type_to_json(args[0])
    return "string"
