"""
Meta-tool: register a local directory package or single .py file as a HydroAgent plugin.

For directories: looks for an existing hydroagent_adapter.py; if absent and
generate_adapter=True, writes a skeleton adapter that the user (or LLM) can fill in.

For single .py files: delegates to add_local_tool().
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Skeleton template written when no hydroagent_adapter.py exists
_ADAPTER_SKELETON = '''\
"""
HydroAgent adapter for {name}.
Generated by add_local_package().  Fill in the methods below.
"""
import sys
from pathlib import Path

# Make the package importable even without pip install
sys.path.insert(0, str(Path(__file__).parent))

from hydroagent.adapters.base import PackageAdapter


class Adapter(PackageAdapter):
    name = "{name}"
    priority = 5  # Adjust: 12 = above hydromodel(10), 5 = generic external

    def can_handle(self, data_source: str, model_name: str) -> bool:
        return model_name == "{name}"

    def supported_operations(self) -> list[str]:
        # List the operations this adapter exposes, e.g. ["analyze", "plot"]
        return []

    # Add one method per operation, e.g.:
    # def analyze(self, workspace: Path, **kw) -> dict:
    #     import {name}
    #     ...
    #     return {{"success": True, ...}}
'''

_SKILL_MD_SKELETON = '''\
# {name} Package Adapter

{description}

## When to use

Call when the user asks about {name}-related analysis or operations.

## Supported operations

*(Fill in after implementing the adapter methods.)*

## Usage example

```python
# The Agent will call these tools automatically:
add_local_package(path="{path}")
# Then the adapter is live and routed via model_name="{name}"
```
'''


def add_local_package(
    path: str,
    name: str | None = None,
    description: str = "",
    priority: int | None = None,
    generate_adapter: bool = True,
    _workspace=None,
    _cfg=None,
) -> dict:
    """Register a local directory package or single .py file as a HydroAgent plugin.

    For directory packages: looks for hydroagent_adapter.py at the package root.
    If not found and generate_adapter=True, a skeleton adapter is written so the
    user or LLM can fill in the implementation.

    For single .py files: call add_local_tool() instead (or this function
    auto-detects and delegates).

    Args:
        path: Absolute or relative path to a local package directory or .py file.
        name: Plugin name (default: directory name or filename stem).
        description: Human-readable description of what the package does.
        priority: Adapter routing priority (default 5 for external plugins).
        generate_adapter: If True and no hydroagent_adapter.py exists, write a skeleton.

    Returns:
        {"success": True, "plugin_name": ..., "adapter_path": ..., "next_steps": [...]}
    """
    resolved = Path(path).expanduser().resolve()

    # Single .py file -> delegate to add_local_tool
    if resolved.is_file() and resolved.suffix == ".py":
        from hydroagent.tools.add_local_tool import add_local_tool
        return add_local_tool(str(resolved), name=name, description=description,
                               _workspace=_workspace, _cfg=_cfg)

    if not resolved.is_dir():
        return {
            "success": False,
            "error": f"Path does not exist or is not a directory: {resolved}",
        }

    pkg_name = name or resolved.name
    adapter_path = resolved / "hydroagent_adapter.py"
    skill_dir = resolved / "hydroagent_adapter_skills"
    created_files: list[str] = []

    # Generate skeleton if missing
    if not adapter_path.exists():
        if not generate_adapter:
            return {
                "success": False,
                "plugin_name": pkg_name,
                "error": (
                    f"No hydroagent_adapter.py found at {adapter_path}. "
                    "Either create one manually or set generate_adapter=True."
                ),
            }
        _prio = priority or 5
        skeleton = _ADAPTER_SKELETON.format(name=pkg_name)
        # Inject custom priority if provided
        if priority is not None:
            skeleton = skeleton.replace("priority = 5", f"priority = {priority}")
        adapter_path.write_text(skeleton, encoding="utf-8")
        created_files.append(str(adapter_path))
        logger.info("[add_local_package] wrote adapter skeleton -> %s", adapter_path)

        # Also write a skill.md template
        skill_dir.mkdir(exist_ok=True)
        skill_md = skill_dir / "skill.md"
        if not skill_md.exists():
            skill_md.write_text(
                _SKILL_MD_SKELETON.format(
                    name=pkg_name, description=description or f"{pkg_name} package",
                    path=str(resolved),
                ),
                encoding="utf-8",
            )
            created_files.append(str(skill_md))

    # Register in plugin registry
    from hydroagent.utils.plugin_registry import PluginRegistry
    registry = PluginRegistry(Path(_workspace) if _workspace else None)
    entry = registry.make_entry(
        name=pkg_name,
        path=str(resolved),
        plugin_type="local_dir",
        adapter_path=str(adapter_path),
        description=description,
    )
    registry.add(entry)

    # Reload adapters so the new plugin is immediately active
    from hydroagent.adapters import reload_adapters
    ws = Path(_workspace) if _workspace else None
    reload_adapters(ws)

    next_steps: list[str] = []
    if created_files:
        next_steps.append(
            f"Adapter skeleton written to {adapter_path}. "
            "Fill in the method bodies (each method should import the package and call it)."
        )
    next_steps.append(
        f"Plugin '{pkg_name}' is now registered. "
        "Use /plugin list to verify, or call the adapter's operations via the Agent."
    )

    return {
        "success": True,
        "plugin_name": pkg_name,
        "plugin_type": "local_dir",
        "adapter_path": str(adapter_path),
        "adapter_existed": not bool(created_files),
        "created_files": created_files,
        "next_steps": next_steps,
    }
